DROP TABLE IF EXISTS METROCARD;

DROP TABLE IF EXISTS JOURNEY;
 
CREATE TABLE METROCARD (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  balance VARCHAR(250)
);


 
CREATE TABLE JOURNEY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  source VARCHAR(250),
  swipeIn TIMESTAMP,
  destination VARCHAR(250),
  swipeOut TIMESTAMP,
  completed BIT DEFAULT 0,
  fare VARCHAR(250),
  metroCardId int 
);
